server:
  port: 18081

## 数据库使用sqlite
spring:
  application:
    name: spring-aop-demo
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: "jdbc:sqlite:.\\spring_aop.db"

### MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

### 分页插件
pagehelper:
  helper-dialect: sqlite
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
